'use client'
import {useEffect,useMemo,useState} from 'react'
import {supabase} from '../../lib/supabase'
import Topbar from '../../components/Topbar'
import {useRouter} from 'next/navigation'
const rupiah=n=>'Rp'+Number(n||0).toLocaleString('id-ID')
export default function AdminPage(){
 const router=useRouter();const[profile,setProfile]=useState(null);const[entries,setEntries]=useState([]);const[products,setProducts]=useState([]);const[employees,setEmployees]=useState([]);const[periods,setPeriods]=useState([]);const[slips,setSlips]=useState([]);const[tab,setTab]=useState('approval');const[msg,setMsg]=useState('');const[newProduct,setNewProduct]=useState({name:'',rate_per_piece:''});const[newPeriod,setNewPeriod]=useState({name:'',start_date:'',end_date:''})
 useEffect(()=>{load()},[])
 async function load(){const {data:{user}}=await supabase.auth.getUser();if(!user){router.push('/');return}const {data:p}=await supabase.from('profiles').select('*').eq('id',user.id).single();if(p?.role!=='admin'){router.push('/employee');return}setProfile(p);const [{data:e},{data:pr},{data:emp},{data:per},{data:s}]=await Promise.all([supabase.from('production_entries').select('*,products(name),profiles!production_entries_employee_id_fkey(full_name)').order('created_at',{ascending:false}).limit(1000),supabase.from('products').select('*').order('name'),supabase.from('profiles').select('*').eq('role','employee').order('full_name'),supabase.from('payroll_periods').select('*').order('start_date',{ascending:false}),supabase.from('payroll_slips').select('*,profiles!payroll_slips_employee_id_fkey(full_name),payroll_periods(name,start_date,end_date)').order('created_at',{ascending:false})]);setEntries(e||[]);setProducts(pr||[]);setEmployees(emp||[]);setPeriods(per||[]);setSlips(s||[])}
 const payroll=useMemo(()=>entries.filter(x=>x.status==='pass').reduce((a,x)=>a+(x.approved_qty||0)*(x.rate_snapshot||0),0),[entries])
 async function log(action,entity_type,entity_id,detail={}){const {data:{user}}=await supabase.auth.getUser();await supabase.from('audit_logs').insert({actor_id:user.id,action,entity_type,entity_id,detail})}
 async function verify(row,status,approved_qty){const patch={status,approved_qty:Number(approved_qty||0),verified_at:new Date().toISOString()};const {error}=await supabase.from('production_entries').update(patch).eq('id',row.id);if(error)setMsg(error.message);else{await log('verify_production','production_entries',row.id,patch);load()}}
 async function addProduct(e){e.preventDefault();const {data,error}=await supabase.from('products').insert({name:newProduct.name,rate_per_piece:Number(newProduct.rate_per_piece),active:true}).select().single();if(error)setMsg(error.message);else{await log('create_product','products',data.id,data);setNewProduct({name:'',rate_per_piece:''});load()}}
 async function addPeriod(e){e.preventDefault();const {data,error}=await supabase.from('payroll_periods').insert(newPeriod).select().single();if(error)setMsg(error.message);else{await log('create_period','payroll_periods',data.id,data);setNewPeriod({name:'',start_date:'',end_date:''});load()}}
 async function generatePayroll(period){const pass=entries.filter(x=>x.status==='pass'&&x.work_date>=period.start_date&&x.work_date<=period.end_date);for(const emp of employees){const empRows=pass.filter(x=>x.employee_id===emp.id);if(!empRows.length)continue;const gross=empRows.reduce((a,x)=>a+(x.approved_qty||0)*(x.rate_snapshot||0),0);const {data:slip,error}=await supabase.from('payroll_slips').upsert({period_id:period.id,employee_id:emp.id,gross_pay:gross,net_pay:gross},{onConflict:'period_id,employee_id'}).select().single();if(error){setMsg(error.message);return}await supabase.from('payroll_items').delete().eq('slip_id',slip.id);const items=empRows.map(x=>({slip_id:slip.id,production_entry_id:x.id,product_name:x.products?.name||'Produk',approved_qty:x.approved_qty,rate_per_piece:x.rate_snapshot,amount:(x.approved_qty||0)*(x.rate_snapshot||0)}));if(items.length){const {error:ie}=await supabase.from('payroll_items').insert(items);if(ie){setMsg(ie.message);return}}}await log('generate_payroll','payroll_periods',period.id,{period:period.name});setMsg('Payroll berhasil dibuat/di-refresh.');load()}
 async function lockPeriod(period){const {error}=await supabase.from('payroll_periods').update({status:'locked',locked_at:new Date().toISOString()}).eq('id',period.id);if(error)setMsg(error.message);else{await log('lock_period','payroll_periods',period.id,{name:period.name});load()}}
 async function setPayment(slip,status){const patch={payment_status:status,updated_at:new Date().toISOString()};if(status==='approved')patch.approved_at=new Date().toISOString();if(status==='paid')patch.paid_at=new Date().toISOString();const {error}=await supabase.from('payroll_slips').update(patch).eq('id',slip.id);if(error)setMsg(error.message);else{await log('payment_status','payroll_slips',slip.id,patch);load()}}
 if(!profile)return <div className="container">Memuat...</div>
 return <><Topbar name={profile.full_name} role="Admin/Master"/><div className="container"><div className="grid grid-4"><div className="card kpi"><div className="label">Payroll Terverifikasi</div><div className="value">{rupiah(payroll)}</div></div><div className="card kpi"><div className="label">Menunggu QC</div><div className="value">{entries.filter(x=>x.status==='pending').length}</div></div><div className="card kpi"><div className="label">Periode Payroll</div><div className="value">{periods.length}</div></div><div className="card kpi"><div className="label">Slip Belum Dibayar</div><div className="value">{slips.filter(s=>s.payment_status!=='paid').length}</div></div></div>
 <div className="tabs">{[['approval','Approval & QC'],['products','Master Tarif'],['periods','Periode Payroll'],['payroll','Payroll & Bayar'],['employees','Karyawan']].map(([k,l])=><button key={k} className={'tab '+(tab===k?'active':'')} onClick={()=>setTab(k)}>{l}</button>)}</div>{msg&&<div className="notice" style={{marginBottom:12}}>{msg}</div>}
 {tab==='approval'&&<div className="card"><h2>Approval Produksi</h2><div className="table-wrap"><table><thead><tr><th>Tanggal</th><th>Penjahit</th><th>Produk</th><th>Diajukan</th><th>Lolos QC</th><th>Status</th><th>Aksi</th></tr></thead><tbody>{entries.map(r=><ApprovalRow key={r.id} row={r} verify={verify}/>)}</tbody></table></div></div>}
 {tab==='products'&&<div className="grid grid-2"><div className="card"><h2>Tambah Produk/Proses</h2><form className="form-stack" onSubmit={addProduct}><div><label>Nama</label><input className="input" value={newProduct.name} onChange={e=>setNewProduct({...newProduct,name:e.target.value})} required/></div><div><label>Tarif/pcs</label><input className="input" type="number" value={newProduct.rate_per_piece} onChange={e=>setNewProduct({...newProduct,rate_per_piece:e.target.value})} required/></div><button className="btn btn-primary">Simpan</button></form></div><div className="card"><h2>Master Tarif</h2><div className="table-wrap"><table><thead><tr><th>Produk</th><th>Tarif</th><th>Status</th></tr></thead><tbody>{products.map(p=><tr key={p.id}><td>{p.name}</td><td><b>{rupiah(p.rate_per_piece)}</b></td><td>{p.active?'Aktif':'Nonaktif'}</td></tr>)}</tbody></table></div></div></div>}
 {tab==='periods'&&<div className="grid grid-2"><div className="card"><h2>Buat Periode Payroll</h2><form className="form-stack" onSubmit={addPeriod}><div><label>Nama periode</label><input className="input" value={newPeriod.name} onChange={e=>setNewPeriod({...newPeriod,name:e.target.value})} required/></div><div><label>Tanggal mulai</label><input className="input" type="date" value={newPeriod.start_date} onChange={e=>setNewPeriod({...newPeriod,start_date:e.target.value})} required/></div><div><label>Tanggal selesai</label><input className="input" type="date" value={newPeriod.end_date} onChange={e=>setNewPeriod({...newPeriod,end_date:e.target.value})} required/></div><button className="btn btn-primary">Buat Periode</button></form></div><div className="card"><h2>Daftar Periode</h2><div className="table-wrap"><table><thead><tr><th>Periode</th><th>Tanggal</th><th>Status</th><th>Aksi</th></tr></thead><tbody>{periods.map(p=><tr key={p.id}><td><b>{p.name}</b></td><td>{p.start_date} s/d {p.end_date}</td><td>{p.status}</td><td><div className="actions"><button className="btn btn-secondary" onClick={()=>generatePayroll(p)}>Generate</button>{p.status==='open'&&<button className="btn btn-primary" onClick={()=>lockPeriod(p)}>Kunci</button>}</div></td></tr>)}</tbody></table></div></div></div>}
 {tab==='payroll'&&<div className="card"><h2>Payroll & Status Pembayaran</h2><div className="table-wrap"><table><thead><tr><th>Periode</th><th>Penjahit</th><th>Bruto</th><th>Bonus</th><th>Potongan</th><th>Netto</th><th>Status</th><th>Aksi</th></tr></thead><tbody>{slips.map(s=><tr key={s.id}><td>{s.payroll_periods?.name}</td><td>{s.profiles?.full_name}</td><td>{rupiah(s.gross_pay)}</td><td>{rupiah(s.bonus)}</td><td>{rupiah(s.deduction)}</td><td><b>{rupiah(s.net_pay)}</b></td><td>{s.payment_status}</td><td><div className="actions">{s.payment_status==='unpaid'&&<button className="btn btn-secondary" onClick={()=>setPayment(s,'approved')}>Setujui</button>}{s.payment_status!=='paid'&&<button className="btn btn-primary" onClick={()=>setPayment(s,'paid')}>Sudah Dibayar</button>}<a className="btn btn-secondary" href={'/slip/'+s.id} target="_blank">Slip</a></div></td></tr>)}</tbody></table></div></div>}
 {tab==='employees'&&<div className="card"><h2>Karyawan</h2><div className="notice">Buat akun karyawan di Supabase Authentication. Profil otomatis dibuat sebagai employee.</div><div className="table-wrap"><table><thead><tr><th>Nama</th><th>Email</th><th>Status</th></tr></thead><tbody>{employees.map(e=><tr key={e.id}><td>{e.full_name}</td><td>{e.email}</td><td>{e.active===false?'Nonaktif':'Aktif'}</td></tr>)}</tbody></table></div></div>}
 </div></>}
function ApprovalRow({row,verify}){const[approved,setApproved]=useState(row.approved_qty||row.submitted_qty||0);return <tr><td>{row.work_date}</td><td>{row.profiles?.full_name||'-'}</td><td>{row.products?.name||'-'}</td><td>{row.submitted_qty}</td><td><input className="input" style={{width:90}} type="number" min="0" max={row.submitted_qty} value={approved} onChange={e=>setApproved(e.target.value)}/></td><td>{row.status}</td><td><div className="actions"><button className="btn btn-primary" onClick={()=>verify(row,'pass',approved)}>PASS</button><button className="btn btn-secondary" onClick={()=>verify(row,'rework',0)}>REWORK</button><button className="btn btn-danger" onClick={()=>verify(row,'reject',0)}>REJECT</button></div></td></tr>}
