'use client'
import {useEffect,useMemo,useState} from 'react'
import {supabase} from '../../lib/supabase'
import Topbar from '../../components/Topbar'
import {useRouter} from 'next/navigation'
const rp=n=>'Rp'+Number(n||0).toLocaleString('id-ID')
export default function EmployeePage(){
 const router=useRouter();const[user,setUser]=useState(null);const[profile,setProfile]=useState(null);const[products,setProducts]=useState([]);const[rows,setRows]=useState([]);const[slips,setSlips]=useState([]);const[productId,setProductId]=useState('');const[qty,setQty]=useState('');const[notes,setNotes]=useState('');const[msg,setMsg]=useState('')
 useEffect(()=>{load()},[])
 async function load(){const {data:{user}}=await supabase.auth.getUser();if(!user){router.push('/');return}setUser(user);const {data:p}=await supabase.from('profiles').select('*').eq('id',user.id).single();if(p?.role==='admin'){router.push('/admin');return}setProfile(p);const [{data:pr},{data:r},{data:s}]=await Promise.all([supabase.from('products').select('*').eq('active',true).order('name'),supabase.from('production_entries').select('*,products(name,rate_per_piece)').eq('employee_id',user.id).order('created_at',{ascending:false}).limit(100),supabase.from('payroll_slips').select('*,payroll_periods(name,start_date,end_date)').eq('employee_id',user.id).order('created_at',{ascending:false}).limit(24)]);setProducts(pr||[]);setRows(r||[]);setSlips(s||[])}
 const pay=useMemo(()=>rows.filter(r=>r.status==='pass').reduce((a,r)=>a+(r.approved_qty||0)*(r.rate_snapshot||0),0),[rows])
 async function submit(e){e.preventDefault();const pr=products.find(x=>x.id===productId);const {error}=await supabase.from('production_entries').insert({employee_id:user.id,product_id:productId,work_date:new Date().toISOString().slice(0,10),submitted_qty:Number(qty),approved_qty:0,status:'pending',notes,rate_snapshot:pr?.rate_per_piece||0});if(error){setMsg(error.message);return}setQty('');setNotes('');setMsg('Produksi berhasil dikirim untuk verifikasi.');load()}
 if(!profile)return <div className="container">Memuat...</div>
 return <><Topbar name={profile.full_name} role="Karyawan"/><div className="container"><div className="grid grid-4"><div className="card kpi"><div className="label">Upah Terverifikasi</div><div className="value">{rp(pay)}</div></div><div className="card kpi"><div className="label">Menunggu</div><div className="value">{rows.filter(r=>r.status==='pending').length}</div></div><div className="card kpi"><div className="label">PASS</div><div className="value">{rows.filter(r=>r.status==='pass').reduce((a,r)=>a+(r.approved_qty||0),0)} pcs</div></div><div className="card kpi"><div className="label">Slip Dibayar</div><div className="value">{slips.filter(s=>s.payment_status==='paid').length}</div></div></div>
 <div className="grid grid-2" style={{marginTop:16}}><div className="card"><h2 style={{marginTop:0}}>Input Produksi</h2>{msg&&<div className="notice">{msg}</div>}<form className="form-stack" onSubmit={submit}><div><label>Produk / Proses</label><select className="input" value={productId} onChange={e=>setProductId(e.target.value)} required><option value="">Pilih</option>{products.map(p=><option key={p.id} value={p.id}>{p.name} · {rp(p.rate_per_piece)}/pcs</option>)}</select></div><div><label>Jumlah selesai</label><input className="input" type="number" min="1" value={qty} onChange={e=>setQty(e.target.value)} required/></div><div><label>Catatan</label><textarea className="input" rows="3" value={notes} onChange={e=>setNotes(e.target.value)}/></div><button className="btn btn-primary">Kirim Produksi</button></form></div><div className="card"><h2 style={{marginTop:0}}>Slip Gaji Saya</h2><div className="table-wrap"><table><thead><tr><th>Periode</th><th>Total</th><th>Status</th><th></th></tr></thead><tbody>{slips.map(s=><tr key={s.id}><td>{s.payroll_periods?.name}</td><td><b>{rp(s.net_pay)}</b></td><td>{s.payment_status}</td><td><a className="btn btn-secondary" href={'/slip/'+s.id}>Lihat</a></td></tr>)}</tbody></table></div></div></div>
 <div className="card" style={{marginTop:16}}><h2 style={{marginTop:0}}>Riwayat Produksi Saya</h2><div className="table-wrap"><table><thead><tr><th>Tanggal</th><th>Produk</th><th>Diajukan</th><th>Lolos</th><th>Status</th><th>Tarif</th><th>Upah</th></tr></thead><tbody>{rows.map(r=><tr key={r.id}><td>{r.work_date}</td><td>{r.products?.name}</td><td>{r.submitted_qty}</td><td>{r.approved_qty}</td><td>{r.status}</td><td>{rp(r.rate_snapshot)}</td><td><b>{rp((r.approved_qty||0)*(r.rate_snapshot||0))}</b></td></tr>)}</tbody></table></div></div></div></>
}
